/* AUTO-GENERATED by scripts/build-data.mjs — 请勿手动编辑 */
window.GH_DATA = {
  "generatedAt": "2026-09-09T07:47:01.634Z",
  "user": {
    "login": "iqingyoung",
    "name": "轩辕青阳",
    "avatar": "https://avatars.githubusercontent.com/u/50099511?v=4",
    "bio": null,
    "publicRepos": 6,
    "followers": 0,
    "htmlUrl": "https://github.com/iqingyoung"
  },
  "totals": {
    "repos": 3,
    "stars": 2,
    "languages": 2
  },
  "repos": [
    {
      "name": "search2chart-mcp",
      "displayName": "search2chart-mcp",
      "url": "https://github.com/iqingyoung/search2chart-mcp",
      "description": "Agent-native charting — turn search, research, and tabular data into inline charts in agent conversations. Native DSH plugin for true inline rendering + cross-agent MCP server with file-link and interactive mode.",
      "stars": 1,
      "language": "JavaScript",
      "topics": [
        "MCP",
        "Charting",
        "Agent-Native"
      ],
      "updatedAt": "2026-09-06T15:23:16Z",
      "featured": true
    },
    {
      "name": "429-throttle-mcp",
      "displayName": "429-throttle-mcp",
      "url": "https://github.com/iqingyoung/429-throttle-mcp",
      "description": "Rate-limited MCP proxy with agent operator skill — eliminate HTTP 429 errors on free LLM APIs. Automatic speed control, conversational parameter tuning, and long-task retrospectives built in.",
      "stars": 1,
      "language": "JavaScript",
      "topics": [
        "MCP",
        "Rate Limiting",
        "RPM / TPM",
        "v1.1"
      ],
      "updatedAt": "2026-09-06T15:23:14Z",
      "featured": true
    },
    {
      "name": "inspidea",
      "displayName": "InspIdea · 灵感卡片",
      "url": "https://github.com/iqingyoung/inspidea",
      "description": "Minimal cross-platform inspiration capture tool. One hotkey to summon, Enter to save. Pure Markdown local-first storage with Notion, Dropbox, and WebDAV sync. Built with Tauri 2 + React.",
      "stars": 0,
      "language": "Rust",
      "topics": [
        "Tauri 2",
        "React",
        "Rust",
        "Markdown",
        "Cross-Platform"
      ],
      "updatedAt": "2026-09-05T13:00:00Z",
      "featured": true
    }
  ],
  "calendar": {
    "total": 51,
    "weeks": [
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 2,
          "level": 2
        },
        {
          "date": null,
          "count": 3,
          "level": 3
        },
        {
          "date": null,
          "count": 4,
          "level": 4
        },
        {
          "date": null,
          "count": 3,
          "level": 3
        },
        {
          "date": null,
          "count": 2,
          "level": 2
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 3,
          "level": 3
        },
        {
          "date": null,
          "count": 4,
          "level": 4
        },
        {
          "date": null,
          "count": 2,
          "level": 2
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 1,
          "level": 1
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 2,
          "level": 2
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ],
      [
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        },
        {
          "date": null,
          "count": 0,
          "level": 0
        }
      ]
    ],
    "source": "fallback"
  }
};
